version: '3.8'

services:
  backend:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3333:3333
    depends_on:
      - db
    volumes:
      - ./UniBlog/blog-backend:/app
    command: [ "npm", "run", "dev" ]

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uniblog
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
